name: run

on:
  push:
    branches: main
  schedule:
    - cron: '30 21 * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install discord_webhook slack-webhook pytz hcskr
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: env 파일 셋업
      env:
        SUPER_ENV: ${{ secrets.ENV }}
      run: |
        echo "$SUPER_ENV" > env.py
    - name: Run
      run: |
        python main.py
